Repository Cognifide/aem-stubs, pull requests merged in 2020-05, with the labels that each got.

#1 Sling query fix / not available on 6.5
  core/src/main/java/com/cognifide/aem/stubs/core/script/ConfigurableStubScriptManager.java
  core/src/main/java/com/cognifide/aem/stubs/core/script/StubScriptRun.java
  gradle/common.gradle.kts
Labels: bug

#2 Add stubbing from json mapping file
  core/src/main/java/com/cognifide/aem/stubs/core/script/ConfigurableStubScriptManager.java
  core/src/main/java/com/cognifide/aem/stubs/core/script/StubScriptManager.java
  moco/src/main/content/jcr_root/var/stubs/moco/samples/hello-world.stub.groovy
  moco/src/main/java/com/cognifide/aem/stubs/moco/MocoStubs.java
  wiremock/src/integTest/java/com/cognifide/aem/stubs/wiremock/HelloWorldMocksIntegrationTest.java
  wiremock/src/main/content/jcr_root/var/stubs/wiremock/samples/hello-world.stub.groovy
  wiremock/src/main/content/jcr_root/var/stubs/wiremock/samples/hello-world.stub.json
  wiremock/src/main/content/jcr_root/var/stubs/wiremock/samples/templating/templates.stub.groovy
  wiremock/src/main/java/com/cognifide/aem/stubs/wiremock/WireMockApp.java
  wiremock/src/main/java/com/cognifide/aem/stubs/wiremock/WireMockConfig.java
  wiremock/src/main/java/com/cognifide/aem/stubs/wiremock/WireMockFileSource.java
  wiremock/src/main/java/com/cognifide/aem/stubs/wiremock/WireMockStubs.java
Labels: enhancement

#3 Working Moco JSON stubs
  README.MD
  build.gradle.kts
  core/src/main/java/com/cognifide/aem/stubs/core/script/ConfigurableStubScriptManager.java
  core/src/main/java/com/cognifide/aem/stubs/core/script/StubScriptManager.java
  core/src/main/java/com/cognifide/aem/stubs/core/util/JcrUtils.java
  moco/src/integTest/java/com/cognifide/aem/stubs/moco/HelloWorldTest.java
  moco/src/main/content/jcr_root/var/stubs/moco/samples/hello-world.stub.groovy
  moco/src/main/content/jcr_root/var/stubs/moco/samples/hello-world.stub.json
  moco/src/main/java/com/cognifide/aem/stubs/moco/MocoStubs.java
  wiremock/src/integTest/java/com/cognifide/aem/stubs/wiremock/HelloWorldTest.java
  wiremock/src/main/java/com/cognifide/aem/stubs/wiremock/WireMockStubs.java
Labels: enhancement

#6 Mappings refactoring
  build.gradle.kts
  core/src/main/java/com/cognifide/aem/stubs/core/ConfigurableStubManager.java
  core/src/main/java/com/cognifide/aem/stubs/core/StubManager.java
  core/src/main/java/com/cognifide/aem/stubs/core/StubReload.java
  core/src/main/java/com/cognifide/aem/stubs/core/Stubs.java
  core/src/main/java/com/cognifide/aem/stubs/core/script/StubScript.java
  core/src/main/java/com/cognifide/aem/stubs/core/script/StubScriptManager.java
  core/src/main/java/com/cognifide/aem/stubs/core/script/StubScriptRun.java
  moco/build.gradle.kts
  moco/src/main/java/com/cognifide/aem/stubs/moco/MocoStubs.java
  wiremock/build.gradle.kts
  wiremock/src/main/java/com/cognifide/aem/stubs/wiremock/WireMockApp.java
  wiremock/src/main/java/com/cognifide/aem/stubs/wiremock/WireMockOptions.java
  wiremock/src/main/java/com/cognifide/aem/stubs/wiremock/WireMockStubs.java
  wiremock/src/main/java/com/cognifide/aem/stubs/wiremock/mapping/MappingSource.java
Labels: refactoring

#25 Secure by default & AEM composite node store alignment
  README.MD
  core/src/main/content/META-INF/vault/filter.xml
  core/src/main/content/jcr_root/conf/stubs/_rep_policy.xml
  core/src/main/content/jcr_root/var/_rep_policy.xml
  core/src/main/java/com/cognifide/aem/stubs/core/ConfigurableStubManager.java
  docs/osgi-config-stub-manager.png
  docs/screenshot.jpg
  moco/README.MD
  moco/src/main/content/META-INF/vault/filter.xml
  moco/src/main/content/jcr_root/conf/stubs/moco/.content.xml
  moco/src/main/content/jcr_root/conf/stubs/moco/samples/.content.xml
  moco/src/main/content/jcr_root/conf/stubs/moco/samples/hello-world.stub.groovy
  moco/src/main/content/jcr_root/conf/stubs/moco/samples/hello-world.stub.json
  wiremock/README.MD
  wiremock/src/main/content/META-INF/vault/filter.xml
  wiremock/src/main/content/jcr_root/conf/stubs/.content.xml
  wiremock/src/main/content/jcr_root/conf/stubs/wiremock/.content.xml
  wiremock/src/main/content/jcr_root/conf/stubs/wiremock/samples/.content.xml
  wiremock/src/main/content/jcr_root/conf/stubs/wiremock/samples/hello-world.stub.groovy
  wiremock/src/main/content/jcr_root/conf/stubs/wiremock/samples/hello-world.stub.json
  wiremock/src/main/content/jcr_root/conf/stubs/wiremock/samples/logo.png
  wiremock/src/main/content/jcr_root/conf/stubs/wiremock/samples/message.json
  wiremock/src/main/content/jcr_root/conf/stubs/wiremock/samples/templating/.content.xml
  wiremock/src/main/content/jcr_root/conf/stubs/wiremock/samples/templating/template.json
  wiremock/src/main/content/jcr_root/conf/stubs/wiremock/samples/templating/templates.stub.groovy
Labels: enhancement

#29 Filters bypass for WireMock
  build.gradle.kts
  buildSrc/build.gradle.kts
  gradle/common.gradle.kts
  wiremock/src/integTest/java/com/cognifide/aem/stubs/wiremock/HelloWorldTest.java
  wiremock/src/main/java/com/cognifide/aem/stubs/wiremock/WireMockStubs.java
  wiremock/src/main/java/com/cognifide/aem/stubs/wiremock/servlet/WireMockFilter.java
  wiremock/src/main/java/com/cognifide/aem/stubs/wiremock/servlet/WireMockPreprocessor.java
Labels: enhancement
